name: Check for compilation failures

on: [push, pull_request]

jobs:
  build:
    name: Check for compilation failures
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Install dependencies
        run: pacman --noconfirm -Syu && pacman --needed --noconfirm -S base-devel git autoconf automake nasm curl mtools llvm clang lld aarch64-linux-gnu-gcc

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Git config
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Build the bootloader (LLVM)
        run: ./bootstrap && ./configure FREESTANDING_TOOLCHAIN=llvm --enable-werror --enable-all && make all && make maintainer-clean

      - name: Build the bootloader (GNU, x86)
        run: ./bootstrap && ./configure FREESTANDING_TOOLCHAIN=gnu --enable-werror --enable-bios --enable-uefi-ia32 --enable-uefi-x86_64 && make all && make maintainer-clean

      - name: Build the bootloader (GNU, aarch64)
        run: ./bootstrap && ./configure FREESTANDING_TOOLCHAIN=aarch64-linux-gnu --enable-werror --enable-uefi-aarch64 && make all && make maintainer-clean
