name: Check for compilation failures

on: [push, pull_request]

jobs:
  build:
    name: Check for compilation failures
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install git build-essential autoconf automake nasm curl mtools clang -y

      - name: Build the bootloader (gcc)
        run: ./autogen.sh CC=gcc --enable-werror && make all && make maintainer-clean

      - name: Build the bootloader (clang)
        run: ./autogen.sh CC=clang --enable-werror && make all && make maintainer-clean
